const stories = [
 {id:2,topic:'Technology',title:'The small machines making a big difference in medicine',author:'Ari Lopez',time:'48 min ago',read:'6 min read',image:'image-lab',summary:'A new generation of diagnostic tools is bringing high-quality healthcare closer to home.'},
 {id:3,topic:'Culture',title:'Why the art of gathering is having a comeback',author:'June Park',time:'1 hr ago',read:'5 min read',image:'image-crowd',summary:'From neighborhood supper clubs to third places, people are finding their way back to one another.'},
 {id:4,topic:'Business',title:'The new math of a four-day workweek',author:'Samir Patel',time:'2 hrs ago',read:'7 min read',image:'image-money',summary:'For companies testing shorter weeks, productivity is just the beginning of the calculation.'},
 {id:5,topic:'Culture',title:'A bookstore built for lingering',author:'Mina Rose',time:'3 hrs ago',read:'4 min read',image:'image-book',summary:'Inside the independent shops turning a quick purchase into an afternoon ritual.'},
 {id:6,topic:'Science',title:'The map hidden in a single drop of seawater',author:'Theo James',time:'4 hrs ago',read:'8 min read',image:'image-ocean',summary:'Marine biologists are using environmental DNA to see the life beneath the waves.'},
 {id:7,topic:'Science',title:'A closer look at our changing night sky',author:'Elena Kim',time:'5 hrs ago',read:'5 min read',image:'image-space',summary:'New telescopes are making the furthest reaches of the universe feel unexpectedly near.'}
];
const lead={id:1,topic:'World',title:'The quiet remaking of cities after the heat',author:'Nia Carter',time:'24 min ago',read:'8 min read',summary:'Across the globe, architects and residents are rebuilding urban life around a hotter reality — one shaded street at a time.'};
let activeTopic='All', query='', saved=JSON.parse(localStorage.getItem('current-saved')||'[]');
const feed=document.querySelector('#story-feed'), savedList=document.querySelector('#saved-list');
function allStories(){return [lead,...stories]}
function toggleSave(id){saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];localStorage.setItem('current-saved',JSON.stringify(saved));render();}
function card(s){const marked=saved.includes(s.id);return `<article class="feed-card" data-id="${s.id}" tabindex="0"><div class="card-image ${s.image}"></div><div class="meta"><b>${s.topic}</b> ${s.read}</div><h3>${s.title}</h3><div class="card-bottom"><span>${s.author} · ${s.time}</span><button class="save-button" data-save="${s.id}" aria-label="${marked?'Remove':'Save'} ${s.title}">${marked?'Saved':'Save'} ↗</button></div></article>`}
function render(){const filtered=stories.filter(s=>(activeTopic==='All'||s.topic===activeTopic)&&`${s.title} ${s.summary}`.toLowerCase().includes(query.toLowerCase()));feed.innerHTML=filtered.map(card).join('');document.querySelector('#result-count').textContent=`${filtered.length} ${filtered.length===1?'story':'stories'}`;document.querySelector('#empty-state').hidden=!!filtered.length;document.querySelector('#saved-count').textContent=saved.length?`(${saved.length})`:'';const savedStories=allStories().filter(s=>saved.includes(s.id));savedList.innerHTML=savedStories.map(s=>`<div class="saved-item"><span><b>${s.topic}</b> · ${s.title}</span><button data-save="${s.id}">Remove</button></div>`).join('');document.querySelector('#saved-empty').textContent=savedStories.length?`${savedStories.length} saved`:'Nothing saved yet';document.querySelector('.lead-story .save-button').innerHTML=(saved.includes(1)?'Saved':'Save')+' <span>↗</span>';}
document.querySelector('#topics').addEventListener('click',e=>{if(!e.target.matches('.topic'))return;activeTopic=e.target.dataset.topic;document.querySelectorAll('.topic').forEach(x=>x.classList.toggle('active',x===e.target));render()});
document.querySelector('#search').addEventListener('input',e=>{query=e.target.value;render()});
document.addEventListener('click',e=>{const button=e.target.closest('[data-save]');if(button){e.stopPropagation();toggleSave(+button.dataset.save);return}if(e.target.closest('.lead-story .save-button'))toggleSave(1);const article=e.target.closest('.feed-card');if(article)openArticle(+article.dataset.id)});
function openArticle(id){const s=allStories().find(x=>x.id===id),modal=document.querySelector('#article-modal');document.querySelector('#article-content').innerHTML=`<div class="modal-meta">${s.topic} · ${s.read}</div><h2>${s.title}</h2><p>By ${s.author} · ${s.time}</p><p>${s.summary}</p><p>This is a sample article view for Current. The app keeps the reading experience deliberate: clear typography, just enough context, and no distractions between you and the story.</p>`;modal.showModal()}
document.querySelector('#close-modal').onclick=()=>document.querySelector('#article-modal').close();
document.querySelector('#menu-button').onclick=()=>{const nav=document.querySelector('#mobile-nav'),open=nav.classList.toggle('open');document.querySelector('#menu-button').setAttribute('aria-expanded',open)};
document.querySelector('#theme-toggle').onclick=()=>document.body.classList.toggle('dark');
document.querySelector('#briefing-button').onclick=()=>openArticle(lead.id);
document.querySelector('#newsletter-form').onsubmit=e=>{e.preventDefault();document.querySelector('#form-note').textContent='You’re on the list. See you tomorrow morning.';e.target.reset()};
render();
